name: DevSecOps & Compliance Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

# This future-proofs the runner for the June 2026 transition
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep/ci
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: ubuntu-latest

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
      - uses: actions/checkout@v6
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci
        env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  security_and_compliance:
    runs-on: ubuntu-latest
    steps:
      # Updated to v5 to support Node 24
      - name: Checkout repository
        uses: actions/checkout@v6

      # 1. SCA & License Compliance: OSV-Scanner
      - name: OSV-Scanner (CVEs & Licenses)
        run: |
          docker run --rm -v ${{ github.workspace }}:/src ghcr.io/google/osv-scanner \
          --licenses="MIT,Apache-2.0,BSD-3-Clause,BSD-2-Clause,ISC,MPL-2.0,0BSD,Python-2.0,CC0-1.0,LGPL-3.0-or-later,BlueOak-1.0.0,CC-BY-4.0" \
          -r /src

      # 2. IaC Compliance: Checkov
      - name: Checkov (SOC2 & CIS Benchmarks)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform,kubernetes,dockerfile
          check: CKV_AWS_CIS,CKV_SOC2_1
          soft_fail: false 